### ISSUE TITLE
Options for highlight & Facet search

### ISSUE THREAD

**Issue by jaychakra** [Highstrike/cakephp-solr-datasource#1]
@Highstrike: Awesome implementation.

I was curious to know is there any options for highlight or faceted search?

**Comment by highstrike** [comment]
It is possible, however I am not familiar with the faceted and highlight components of Solr or how they can be implemented in [Solarium](http://www.solarium-project.org/).

I've looked [here](https://github.com/solariumphp/solarium/tree/master/examples) but all the examples are 2 years old and the syntax differs a bit from how i've built the query in my datasource.

However that is not to say it is impossible, some changes must be made on the [read function](https://github.com/Highstrike/cakephp-solr-datasource/blob/master/Model/Datasource/SolrSource.php#L78) in order to support those features.

Unfortunately I do not have the time to experiment with Solr past what my project required. You can try adding those features yourself and if you succeed you can always make a pull request here with your changes :)

You could also use Solarium by itself in your cake application.
Good luck
